In [7]:
import pandas as pd
import numpy as np

In [8]:
filepath_block_1 = 'data/block1_academic_student_response.csv'
filepath_block_2 = 'data/Regressors - Block 2 Feedback Survey (Responses) - Form Responses 1.csv'
filepath_block_3 = 'data/Regressors - Block 3 Feedback Survey (Responses) - Form Responses 1.csv'

df_block_1 = pd.read_csv(filepath_block_1)
df_block_2 = pd.read_csv(filepath_block_2)
df_block_3 = pd.read_csv(filepath_block_3)

In [9]:
df_block_1.columns

Index(['Timestamp',
       'Q1: How satisfied are you with the structure of the program? (potential areas to think about: course logistics, grading system, division into sections, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE COURSE (that's for another section)',
       'If you have anything to share for Q1, please use the space below to share your feedback',
       'Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)',
       'If you have anything to share for Q2, please use the space below to share your feedback',
       'Q3. How satisfied are you with the Instructors and Instruction Quality of the program? (potential areas to think about: lecture pace, areas of excellence, areas of improvement, etc.)',
       'If you have anything to share for Q3, please use the space below to share your feedback',
       'Q4. How satisfied are you with the Communication Method/Effectiveness of the program? (potential areas to think about: using Slack, using course-specific websites, etc.)',
       'If you have anything to share for Q4, please use the space below to share your feedback',
       'Q5. How challenging has the program been thus far? (potential areas to think about: the difficulty of lectures, the difficulty of the labs/worksheets, the difficulty of the exams, etc.)',
       'If you have anything to share for Q5, please use the space below to share your feedback',
       'Q6. How has balancing the course workload been so far? (potential areas to think about: lectures, pre-lecture workload, labs, worksheets, etc.)',
       'If you have anything to share for Q6, please use the space below to share your feedback',
       'What are some things that's working well for you regarding the academic-portion of this program (i.e. positive remarks)',
       'What are some things that's absolutely NOT working well for you regarding the academic-portion of this program (i.e. negative remarks)',
       'If you have anything else to share with the instructors and program facilitators, leave your comment/feedback here! '],
      dtype='object')

In [10]:
df_block_2.columns

Index(['Timestamp',
       'What sports would like you like me to plan in the upcoming weeks? ',
       'How often would you like the sports events to happen? ',
       'Which of the following events would you be most interested in attending? (Select al that apply)',
       'How frequenent would you like to have a social event?',
       'Would you be interested in participating in study groups outside of class?',
       'Q1: How satisfied are you with the structure of the program? (potential areas to think about: course logistics, grading system, division into sections, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE COURSE (that's for another section)',
       'If you have anything to share for Q1, please use the space below to share your feedback',
       'Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)',
       'If you have anything to share for Q2, please use the space below to share your feedback',
       'Q3. How satisfied are you with the Instructors and Instruction Quality of the program? (potential areas to think about: lecture pace, areas of excellence, areas of improvement, etc.)',
       'If you have anything to share for Q3, please use the space below to share your feedback',
       'Q4. How satisfied are you with the Communication Method/Effectiveness of the program? (potential areas to think about: using Slack, using course-specific websites, etc.)',
       'If you have anything to share for Q4, please use the space below to share your feedback',
       'Q5. How challenging has the program been thus far? (potential areas to think about: the difficulty of lectures, the difficulty of the labs/worksheets, the difficulty of the exams, etc.)',
       'If you have anything to share for Q5, please use the space below to share your feedback',
       'Q6. How has balancing the course workload been so far? (potential areas to think about: lectures, pre-lecture workload, labs, worksheets, etc.)',
       'If you have anything to share for Q6, please use the space below to share your feedback',
       'What are some things that's working well for you regarding the academic-portion of this program (i.e. positive remarks)',
       'What are some things that's absolutely NOT working well for you regarding the academic-portion of this program (i.e. negative remarks)',
       'If you have anything else to share with the instructors and program facilitators, leave your comment/feedback here! ',
       'Column 21', 'How stressful did you find the block 2?',
       'Have you had a chance to try any of the resources? If so, I’d love to hear your feedback!',
       'How can we help you?',
       'Have you attended any career-related events or workshops so far?',
       'If so, could you share your experience and feedback?'],
      dtype='object')

In [11]:
df_block_3.columns

Index(['Timestamp',
       'What sports would like you like me to plan in the upcoming weeks? ',
       'What is your skiing level? (only answer the following if you are interested in going skiing) ',
       'How much are you willing to spend in total? (Rentals, tickets, transportation etc...)',
       'Where would you rather go? ',
       'What social events would you like to be plan in the upcoming weeks? ',
       'If you have not attented a social event yet, why do you think that is? ',
       'Q1: How satisfied are you with the structure of the program? (potential areas to think about: course logistics, grading system, division into sections, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE COURSE (that's for another section)',
       'If you have anything to share for Q1, please use the space below to share your feedback',
       'Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)',
       'If you have anything to share for Q2, please use the space below to share your feedback',
       'Q3. In general, how satisfied are you with the Instructors and Instruction Quality of the program? (potential areas to think about: lecture pace, areas of excellence, areas of improvement, etc.)',
       'Q4. How satisfied are you with the Communication Method/Effectiveness of the program? (potential areas to think about: using Slack, using course-specific websites, etc.)',
       'If you have anything to share for Q4, please use the space below to share your feedback',
       'Q5. How challenging has the program been thus far? (potential areas to think about: the difficulty of lectures, the difficulty of the labs/worksheets, the difficulty of the exams, etc.)',
       'If you have anything to share for Q5, please use the space below to share your feedback',
       'Q6. How has balancing the course workload been so far? (potential areas to think about: lectures, pre-lecture workload, labs, worksheets, etc.)',
       'If you have anything to share for Q6, please use the space below to share your feedback',
       'If you have anything else to share with the instructors and program facilitators, leave your comment/feedback here! ',
       'DSCI 513 - Database (Gittu - Lectures)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 513 - Database (Gittu - Lectures)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 513 - Database (Andy - Labs)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 513 - Database (Andy - Labs)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 522 - Data Science Workflows (Daniel)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 522 - Data Science Workflows (Daniel)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 561 - Regression (Payman)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 561 - Regression (Payman)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 573 - Feature & Model Selection (Joel)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 573 - Feature & Model Selection (Joel)\nIn one or two sentences, constructively, what could be improved about this course?',
       'How stressful do you find the block 3?',
       'What is the biggest challenge affecting your mental health this block? ',
       'What additional mental health resources or services would you like to see provided?',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Resume/CV Workshops]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Mock Interviews]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Industry Networking Events]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Job Search Strategies]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Technical Skill Development]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Soft Skills Development]',
       'If you had a one-on-one session with our MDS Career Advisor, please share your feedback.',
       'How would you rate the workshop overall?',
       'How relevant was the content  to you?',
       'What was the most valuable insight or learning you gained from the workshop?',
       'What topics or issues would you like to see covered in future workshops?'],
      dtype='object')

In [12]:
# trendline
column_starts_with = 'Q2' 
filtered_df_block_1 = df_block_1.loc[:, df_block_1.columns.str.startswith(column_starts_with)]
filtered_df_block_1.dropna(inplace=True)

filtered_df_block_2 = df_block_2.loc[:, df_block_2.columns.str.startswith(column_starts_with)]
filtered_df_block_2.dropna(inplace=True)

filtered_df_block_3 = df_block_3.loc[:, df_block_3.columns.str.startswith(column_starts_with)]
filtered_df_block_3.dropna(inplace=True)

/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_69266/1637919991.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_block_1.dropna(inplace=True)
/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_69266/1637919991.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_block_2.dropna(inplace=True)
/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_69266/1637919991.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_block_3.dropna(inplace=True)

In [13]:
df_block_1_value_count = filtered_df_block_1.apply(pd.Series.value_counts)
df_block_2_value_count = filtered_df_block_2.apply(pd.Series.value_counts)
df_block_3_value_count = filtered_df_block_3.apply(pd.Series.value_counts)

df_combined = pd.concat([df_block_1_value_count, df_block_2_value_count, df_block_3_value_count], ignore_index=False, axis=1)
df_combined

,"Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)","Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)","Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)"
"Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.) Note: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)",,,
Satisfied,17,19,14
Neutral,13,12,11
Dissatisfied,12,4,4
Very satisfied,5,3,1
Very dissatisfied,2,2,1

array(['Mostly Manageable', 'Extremely difficult to manage',
       'Frequently Overwhelming', 'Sometimes Overwhelming'], dtype=object)

In [ ]:
def convert_values(df):
    satisfaction_mapping = {
        "Very dissatisfied": -2,
        "Dissatisfied": -1,
        "Neutral": 0,
        "Satisfied": 1,
        "Very satisfied": 2
    }   

    q5_mapping = {
        "Extremely Challenging": -2,
        "Frequently Overwhelming": -1,
        "Sometimes Overwhelming": 0,
        "Mostly Manageable": 1,
        "Very Manageable": 2
    }

    q6_mapping = {
        "Extremely difficult to manage": -2,
        "Frequently Overwhelming": -1,
        "Sometimes Overwhelming": 0,
        "Mostly Manageable": 1,
        "Very Manageable": 2
    }

    challenging_column = df.columns[df.columns.str.startswith("Q6")]
    satisfaction_column = df.columns.difference(challenging_column)

    df[satisfaction_column] = df[satisfaction_column].applymap(lambda x: satisfaction_mapping.get(x, x))
    df[challenging_column] = df[challenging_column].applymap(lambda x: q6_mapping.get(x, x))

    return df

In [32]:
df_block_1_mapped = convert_values(filtered_df_block_1)
df_block_1_mapped

/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_55689/1541833874.py:21: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[satisfaction_column] = df[satisfaction_column].applymap(lambda x: satisfaction_mapping.get(x, x))
/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_55689/1541833874.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[satisfaction_column] = df[satisfaction_column].applymap(lambda x: satisfaction_mapping.get(x, x))
/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_55689/1541833874.py:22: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[challenging_column] = df[challenging_column].applymap(lambda x: challenging_mapping.get(x, x))
/var/folders/8b/lb1cxfqj6zx5dtq789h2k8xr0000gn/T/ipykernel_55689/1541833874.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[challenging_column] = df[challenging_column].applymap(lambda x: challenging_mapping.get(x, x))

,"Q1: How satisfied are you with the structure of the program? (potential areas to think about: course logistics, grading system, division into sections, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE COURSE (that's for another section)","Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)","Q3. How satisfied are you with the Instructors and Instruction Quality of the program? (potential areas to think about: lecture pace, areas of excellence, areas of improvement, etc.)","Q4. How satisfied are you with the Communication Method/Effectiveness of the program? (potential areas to think about: using Slack, using course-specific websites, etc.)","Q5. How challenging has the program been thus far? (potential areas to think about: the difficulty of lectures, the difficulty of the labs/worksheets, the difficulty of the exams, etc.)","Q6. How has balancing the course workload been so far? (potential areas to think about: lectures, pre-lecture workload, labs, worksheets, etc.)"
0,0,2,2,2,Moderately Challenging,1
1,-1,-1,0,0,Extremely Challenging,-2
2,0,0,0,1,Very Challenging,-1
3,-1,-1,0,0,Extremely Challenging,-1
5,1,1,1,1,Moderately Challenging,0
6,-1,-1,0,0,Moderately Challenging,-2
7,1,0,1,2,Moderately Challenging,1
8,1,1,0,0,Moderately Challenging,-2
9,-2,2,-1,-1,Extremely Challenging,-1
10,1,0,0,1,Moderately Challenging,-1
11,0,0,0,-1,Slightly Challenging,1
12,0,-2,0,0,Very Challenging,-1
13,1,1,2,0,Extremely Challenging,-1
14,-1,1,1,2,Slightly Challenging,1
15,-1,-1,1,2,Moderately Challenging,0
16,1,1,2,0,Moderately Challenging,1
17,0,-1,1,1,Moderately Challenging,-1
18,0,-1,1,0,Moderately Challenging,0
19,1,2,0,2,Moderately Challenging,1
20,1,1,1,2,Very Challenging,-1
21,0,1,1,1,Moderately Challenging,0
22,-1,-1,-1,-1,Very Challenging,-2
23,0,-1,1,-1,Not Challenging at all,1
24,-2,0,2,0,Extremely Challenging,-1
25,1,1,1,1,Slightly Challenging,1
26,-1,1,-1,1,Very Challenging,-1
27,0,1,0,1,Very Challenging,-1
28,-2,0,0,-1,Very Challenging,0
29,1,-1,0,1,Very Challenging,-2
30,1,1,1,2,Very Challenging,-1
31,0,0,0,1,Slightly Challenging,1
33,2,1,2,2,Moderately Challenging,0
34,-2,-2,-2,-2,Very Challenging,-2
35,1,1,1,1,Slightly Challenging,1
36,1,0,2,2,Very Challenging,-1
37,1,0,0,2,Very Challenging,-2
38,-1,0,-1,1,Moderately Challenging,1
39,0,-1,1,2,Slightly Challenging,1
40,-1,-1,-1,-1,Very Challenging,-1
41,1,1,0,2,Slightly Challenging,0
42,0,0,0,1,Extremely Challenging,-2
43,1,1,1,1,Extremely Challenging,-2
44,1,1,1,1,Moderately Challenging,0
45,0,0,1,1,Moderately Challenging,0
46,-1,2,1,1,Extremely Challenging,0
47,0,2,1,1,Moderately Challenging,1
48,1,1,1,1,Slightly Challenging,1
49,0,-1,-1,0,Extremely Challenging,-2
50,0,0,0,1,Extremely Challenging,-1

In [39]:
df_block_3.columns

Index(['Timestamp',
       'What sports would like you like me to plan in the upcoming weeks? ',
       'What is your skiing level? (only answer the following if you are interested in going skiing) ',
       'How much are you willing to spend in total? (Rentals, tickets, transportation etc...)',
       'Where would you rather go? ',
       'What social events would you like to be plan in the upcoming weeks? ',
       'If you have not attented a social event yet, why do you think that is? ',
       'Q1: How satisfied are you with the structure of the program? (potential areas to think about: course logistics, grading system, division into sections, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE COURSE (that's for another section)',
       'If you have anything to share for Q1, please use the space below to share your feedback',
       'Q2. How satisfied are you with the assessment structure of the program? (potential areas to think about: cheatsheets, exam dates and availabilities, labs and worksheets, etc.)\n\nNote: DO NOT INCLUDE YOUR FEEDBACK ON THE DIFFICULTY OF THE EXAM (that's for another section)',
       'If you have anything to share for Q2, please use the space below to share your feedback',
       'Q3. In general, how satisfied are you with the Instructors and Instruction Quality of the program? (potential areas to think about: lecture pace, areas of excellence, areas of improvement, etc.)',
       'Q4. How satisfied are you with the Communication Method/Effectiveness of the program? (potential areas to think about: using Slack, using course-specific websites, etc.)',
       'If you have anything to share for Q4, please use the space below to share your feedback',
       'Q5. How challenging has the program been thus far? (potential areas to think about: the difficulty of lectures, the difficulty of the labs/worksheets, the difficulty of the exams, etc.)',
       'If you have anything to share for Q5, please use the space below to share your feedback',
       'Q6. How has balancing the course workload been so far? (potential areas to think about: lectures, pre-lecture workload, labs, worksheets, etc.)',
       'If you have anything to share for Q6, please use the space below to share your feedback',
       'If you have anything else to share with the instructors and program facilitators, leave your comment/feedback here! ',
       'DSCI 513 - Database (Gittu - Lectures)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 513 - Database (Gittu - Lectures)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 513 - Database (Andy - Labs)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 513 - Database (Andy - Labs)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 522 - Data Science Workflows (Daniel)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 522 - Data Science Workflows (Daniel)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 561 - Regression (Payman)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 561 - Regression (Payman)\nIn one or two sentences, constructively, what could be improved about this course?',
       'DSCI 573 - Feature & Model Selection (Joel)\nIn one or two sentences, constructively, what's working well in the course? ',
       'DSCI 573 - Feature & Model Selection (Joel)\nIn one or two sentences, constructively, what could be improved about this course?',
       'How stressful do you find the block 3?',
       'What is the biggest challenge affecting your mental health this block? ',
       'What additional mental health resources or services would you like to see provided?',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Resume/CV Workshops]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Mock Interviews]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Industry Networking Events]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Job Search Strategies]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Technical Skill Development]',
       'How would you rate your interest in attending the following career-related events, with 1 being the least interested and 5 being the most interested? [Soft Skills Development]',
       'If you had a one-on-one session with our MDS Career Advisor, please share your feedback.',
       'How would you rate the workshop overall?',
       'How relevant was the content  to you?',
       'What was the most valuable insight or learning you gained from the workshop?',
       'What topics or issues would you like to see covered in future workshops?'],
      dtype='object')

In [57]:
!pip3 install tabulate

Collecting tabulate
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Installing collected packages: tabulate
Successfully installed tabulate-0.9.0

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python3.12 -m pip install --upgrade pip

In [21]:

from tabulate import tabulate

col_per_prof = {
    'gittu': df_block_3.iloc[:, 19:21].dropna(),
    'andy': df_block_3.iloc[:, 21:23].dropna(),
    'daniel': df_block_3.iloc[:, 23:25].dropna(),
    'payman': df_block_3.iloc[:, 25:27].dropna(),
    'joel': df_block_3.iloc[:, 27:29].dropna()
}

print(tabulate(col_per_prof['joel'], headers="keys", tablefmt="fancy_grid"))

# Pretty display

╒════╤══════════════════════════════════════════════════════════════════════════════════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╕
│    │ DSCI 573 - Feature & Model Selection (Joel)                                                      │ DSCI 573 - Feature & Model Selection (Joel)                                                                                                                                            │
│    │ In one or two sentences, constructively, what's working well in the course?                      │ In one or two sentences, constructively, what could be improved about this course?                                                                                                     │
╞════╪══════════════════════════════════════════════════════════════════════════════════════════════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ 13 │ The could notes are very good.                                                                   │ I could do with some practice for this course because it seems very subjective.                                                                                                        │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 15 │ Explains motivation before teaching concepts. Leaves room for discussions.                       │ While I appreciate a cheatsheet being made for us, I wish I had the freedom to choose between it or custom-made one by myself.                                                         │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 17 │ Am struggling to keep up                                                                         │ I don't know honestly                                                                                                                                                                  │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 18 │ Not so sure                                                                                      │ better explanations and more examples                                                                                                                                                  │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 19 │ Presentation slides are very good, gives an overall general topic of the lecture notes           │ Homework too long                                                                                                                                                                      │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 20 │ Super interesting topic. I thoroughly enjoy it.                                                  │ Labs could be made shorter.                                                                                                                                                            │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 23 │ ppt instead of ntoes                                                                             │ add more contents from notes, align more with notes                                                                                                                                    │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 24 │ I appreciate that joel tries to make an effort to keep the class engaged throughout the lecture. │ There's way too much material in this one course. It seems like the labs are also super dense and I spent a whole day working on it. If the labs could be shorter that would be great. │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 25 │ Detailed lecture notes                                                                           │ Excessive amount of material to be covered in single lectures. Lack of clarity over what's optional and what isn't.                                                                    │
├────┼──────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 26 │ Interactiveness                                                                                  │ The slides order deviate from notes too much                                                                                                                                           │
╘════╧══════════════════════════════════════════════════════════════════════════════════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╛